### PR TITLE
Add PR instructions

### PR DESCRIPTION
**Pull request by plttn**
Hopefully this cuts down on people sending PR against master.

### CODE REVIEW

**Comment by ashawley** [comment]
I don't think more prose in the README helps any.  It's just more stuff people will fail to read.  What you want to add is a `.github/PULL_REQUEST_TEMPLATE.md` file.

**Comment by johnotander** [comment]
I like the idea of this, but I think we should prolly go a step further and link to some relevant docs to help out the git/pixyll users that are a little bit confused.

**Comment by johnotander** [comment]
Hey @plttn, mind perhaps removing the additional readme section and instead adding it to the PR template? Perhaps with an additional link to how git works? 💟

**Comment by plttn** [comment]
Went ahead and added a doc I think is relevant, but don't know if it's the most ideal one.

**Comment by johnotander** [comment]
Thanks!

**Pull request merged**
