### PR TITLE
google analytics in prod only

### PR DESCRIPTION
**Pull request by kartsims**
Prevents analytics data from being added while developing/writing posts

### CODE REVIEW

**Comment by bartekpl** [comment]
As far as I remember, this does not require another variable - all you need to do is to launch dev with second config file (using `--config`) and overwrite the GA setting in your `_config-dev.yml` (make it blank).

**Comment by kartsims** [comment]
I was using your theme without any `config-dev.yml` file (I don't really need it) and I ran into the issue of local pages being logged in GA. I thought others might have it too.

I don't think anyone would need to implement GA anywhere else than production but if you think this PR is irrelevant, you may just close it.

**Comment by bartekpl** [comment]
My comment was to point out that such feature already exists, not that it's irrelevant :). You are suggesting another setting in a theme (one of many), when a feature that does what you want is built into the engine.

**Comment by kartsims** [comment]
Oh OK !

I didn't mean to suggest a new setting (`config.yml` remains the same), but to enhance the default theme by considering the existing `google_analytics` setting should be ignored when Jekyll's environment isn't `production`.

I (now) know this can be done otherwise, I just thought the default behavior could be different.

**Comment by johnotander** [comment]
Thanks for the PR! I'm going to opt to not include this though since it's more of a project specific one off. There is a lot of noise typically in GA data anyway (bots/scrapers/etc).

**Pull request closed without merging**
