### PR TITLE
Added support for using AJAX on the contact form.

### PR DESCRIPTION
**Pull request by Joshfindit**
In _config.yml, set `ajaxify_contact_form: true` in order to AJAXify.

screenshot 2015-09-05 22 58 29

*Note: The "Thanks" pages at `/thanks/index.html` is no longer used in this case, but is still generated.*

### CODE REVIEW

**Comment by johnotander** [comment]
Awesome, thanks @Joshfindit ! :confetti_ball: :confetti_ball: 

One minor nit, though. Could you please rename `_includes/ajaxify_content_form.js` to `_includes/ajaxify_content_form.html` (it's technically still an html partial despite it only consisting of embedded js)?

Once that's done I'd be happy to merge!

**Comment by Joshfindit** [comment]
Done and done. Cheers :)

**Comment by Joshfindit** [comment]
Done and done.
Cheers :)

**Comment by johnotander** [comment]
:dancers:

**Comment by tgaeta** [comment]
@Joshfindit can you troubleshoot Issue https://github.com/johnotander/pixyll/issues/213 please? I can't seem to get the ajax version working.

**Pull request merged**
