### PR TITLE
Revamp CSS

### PR DESCRIPTION
**Pull request by johnotander**
TODO:

- [x] Add the form styling
- [x] Add pagination styling
- [x] Post list spacing
- [x] Syntax highlighting
- [x] Fix type scale
- [x] Fix header nav on tablet
- [x] Add width/font size variables
- [x] Fix the footer, use `flex`
- [x] Add more variables wherever appropriate
- [x] Improve line number formatting (#117)
- [x] Add announcing Pixyll 2.0 post
- [x] Fix alignment of blockquote footers
- [ ] Heavily test for CSS regressions
- [ ] Test on an iPhone
- [ ] Test with animations, icons, and disqus
- [ ] Test on an iPad
- [ ] Test on an Android phone
- [ ] Test on an Android tablet

### CODE REVIEW

**Comment by marste** [comment]
At the line 238 of _basscss.scss, I added:
"word-wrap:break-word;"

and

At line 263 of _main.scss, I added:

pre, code {
  font-family: Menlo, Monaco, monospace
  background: none repeat scroll 0% 0% #F0F8FF;
  font-size: 16px;
}

**Comment by johnotander** [comment]
Thanks @marste !

**Comment by alejorivera** [comment]
Are you guys still moving forward with this PR? Would love to see this happen.

**Comment by anissen** [comment]
There's some really good stuff in the PR. I would love to see it being completed and merged :+1:

**Comment by sindresorhus** [comment]
@johnotander Anything I can help with to get this moving forward? I'm planning on creating a blog and really want to use Pixyll, but the current syntax highlighting is a big turn-off, so was hoping to be able to use Pixyll 2.0.

**Comment by johnotander** [comment]
Hey @sindresorhus !

Thanks for offering to help.

Something that would be extremely helpful is testing for visual bugs and regressions  on devices/browsers once I complete the CSS revamp. I've got some time this afternoon so I can attempt to finalize the new CSS to get things ready for testing and publishing 2.0. I'll keep you posted.

Glad to see you guys like where this is heading @alejorivera and @anissen. Hopefully I'll have this ready to merge today.

**Comment by johnotander** [comment]
2.0.0 has been merged, tagged, and deployed to www.pixyll.com. Please let me know if you encounter any issues or have any tweaks in mind. I will continue testing on more devices/browsers and breaking out some properties into Sass variables (I'm still missing quite a few).

Thanks all! :confetti_ball: :beers: :dancers:

**Comment by alejorivera** [comment]
Congrats! Looking forward to upgrading :)

**Pull request merged**
