### PR TITLE
Update

### PR DESCRIPTION
**Pull request by bogasaur**

### CODE REVIEW

**Comment by johnotander** [comment]
Looks like this is pointed at the wrong fork : )

**Comment by bogasaur** [comment]
Must've done something wrong. Huge newb here. I forked your Pixyll theme
(huge fan btw). Did I fix it yet, or no?

**Comment by johnotander** [comment]
Not a problem. Glad you like it. It's all fixed on my end.

**Comment by bogasaur** [comment]
Was it a huge bother? My bad, man :/ I've actually used Pixyll once before
but I think I copy pasted the files before. This time I decided to fork it.
Can't thank you enough.

**Comment by johnotander** [comment]
Nope, not a bother at all. Just had to click a "Close" button : )

**Comment by bogasaur** [comment]
Sweet. Have a good one John.

**Pull request closed without merging**
