### PR TITLE
added support for txtpen

### PR DESCRIPTION
**Pull request by rickyhan**

### CODE REVIEW

**Comment by rickyhan** [comment]
txtpen is the only service that provides highlighting and in-text commenting similar to Medium. I think adding txtpen in the official documentation will benefit new Jekyll users and bring web annotation to more people.

Thanks in advance.
Ricky

**Comment by johnotander** [comment]
V cool idea and thanks for the PR. I'm going to think on this a bit to determine if I want to include it in this project (as I get the time). Will get back in the next week or so.

Also, if any other Pixyll users want to weigh in here, please do. Thanks in advance.

**Comment by rickyhan** [comment]
Thank you very much. Also checkout txtpen in the official jekyll docs. https://jekyllrb.com/docs/extras/#web-highlights-and-commenting

**Comment by johnotander** [comment]
Thanks for the PR!

**Pull request merged**
